apiVersion: v1
data:
  statsd-get.sh: |
    #!/bin/sh
    while (sleep ${1});
    do
      for schedule in $(/velero schedule get| grep Enabled | awk '{print $1}');
      do
        echo ${schedule};
        COUNT=0;
        COUNT=$(/velero backup get -l velero.io/schedule-name=${schedule}| grep -v NAME | wc -l);
        statsd-client.sh  "velero.backup.active.total.${schedule}:${COUNT}|g";
      done;
    done
kind: ConfigMap
metadata:
  name: statsd-get
  namespace: velero
(local_test) [root@optibet backup]# cat configmaps_statsd_mapping.yaml
apiVersion: v1
data:
  statsd_mapping.conf: |
    mappings:
      - match: "velero.backup.active.total.*"
        name: "velero_backup_active_total"
        labels:
          schedule: "$1"
kind: ConfigMap
metadata:
  name: statsd-mapping
  namespace: velero
