apiVersion: v1
data:
  statsd_mapping.conf: |
    mappings:
      - match: "velero.backup.active.total.*"
        name: "velero_backup_active_total"
        labels:
          schedule: "$1"
kind: ConfigMap
metadata:
  name: statsd-mapping
  namespace: velero
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: statsd
  namespace: velero
spec:
  endpoints:
  - path: /metrics
    port: tcp
    scheme: http
  namespaceSelector:
    matchNames:
    - velero
  selector:
    matchLabels:
      app: statsd-exporter
